### PR TITLE
Updated The Main.html page according to the #12 issues.

### PR DESCRIPTION
**Pull request by c0d3-br34k3r**
**For Issue #12**

**1. Remove the white margins which closes the container "Start Working With:"  
2. Gave a padding of 150px before the heading "Start Working With:" and a padding of 100 px where the container ends.
3. Made the whole website more responsive by adding bootstrap. The homepage is now responsive for any device from mobile to desktop.
4. Added a few effects to the buttons.
5. Updated the Team Members and Linked their github profile. Also updated the Homepage screenshot in README.md
6. Improved the overall quality of the main.html page.**

### CODE REVIEW

**Comment by c0d3-br34k3r** [comment]
Updated the Homepage screenshot in README.md. You can have a look @simranquirky

**Comment by simranquirky** [comment]
Hey @TheInvincibleLearner everything looks fine, but the gaps between those three columns looks too wide , can you reduce it.

**Comment by c0d3-br34k3r** [comment]
> Hey @TheInvincibleLearner everything looks fine, but the gaps between those three columns looks too wide , can you reduce it.

then should i make it 4 buttons in a row ???

**Comment by simranquirky** [comment]
> > Hey @TheInvincibleLearner everything looks fine, but the gaps between those three columns looks too wide , can you reduce it.
> 
> then should i make it 4 buttons in a row ???

Ya that would be great I think.

**Comment by c0d3-br34k3r** [comment]
> > > Hey @TheInvincibleLearner everything looks fine, but the gaps between those three columns looks too wide , can you reduce it.
> > 
> > 
> > then should i make it 4 buttons in a row ???
> 
> Ya that would be great I think.

okay give me 10 mins. I am doing it.

**Comment by c0d3-br34k3r** [comment]
> > > Hey @TheInvincibleLearner everything looks fine, but the gaps between those three columns looks too wide , can you reduce it.
> > 
> > 
> > then should i make it 4 buttons in a row ???
> 
> Ya that would be great I think.

@simranquirky hey Its updated. Have a look at the spacing and let me know.

**Review by simranquirky — APPROVED** [review]
Great!

**Comment by c0d3-br34k3r** [comment]
> Great!

Hey @simranquirky there was a slight mistake from my side for the readme.md update. Please make the following change -

**Replace Line 14 to 20 with the following code for README.md -** 


The Home Page Of The Website !!!<br>

[homepage](https://user-images.githubusercontent.com/77530270/135763120-10034f6f-7d55-4d08-90ca-9a0638c9a8aa.png)

TO UNDERSTAND THE PROJECT BETTER REFER [THIS PAGE](https://simranquirky.github.io/main.html)

[Screenshot (502)](https://user-images.githubusercontent.com/77530270/135854107-ac9cb856-3ab3-4e9c-8b31-245ee17230ba.jpg)


**Add the exclamation sign before [homepage] and [Screenshot (502)] in the above code.**

I made a mistake in pasting the image links. I wont create a pr for this small change since it is equivalent to spam. Hope you will make the change and let me know.

**Comment by c0d3-br34k3r** [comment]
> Great!

@simranquirky please add the hacktoberfest accepted label for this pull request if you liked my work as well.

**Pull request merged**
