### PR TITLE
Created Index page along with "Get Started" button

### PR DESCRIPTION
**Pull request by c0d3-br34k3r**
For Issue #7 

1. Added the index.html page which will be the landing page of the WebApp. 
2. Added a colorful 'GET STARTED' button which will redirect to main.html page
3. Made the whole website more responsive by adding containers and sections.
4. Added a few small effects.

### CODE REVIEW

**Comment by simranquirky** [comment]
Please Attach one screenshot in the description of what the page looks like.

**Comment by c0d3-br34k3r** [comment]
> Please Attach one screenshot in the description of what the page looks like.

Added the screenshot in the description of the readme.md @simranquirky 

[This is the link](https://github.com/TheInvincibleLearner/simranquirky.github.io/blob/indexpage/README.md) 

Have a look at it and let me know. Kept the same theme and background image.

**Review by simranquirky — APPROVED** [review]
Awesome!

**Comment by c0d3-br34k3r** [comment]
> Awesome!

Thanks a lot !!!

**Pull request merged**
